---
title: "R_epidemiology_book"
author: "Diego"
date: "2024-06-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basics

```{r}
library(Epi)
data(births)
stat.table
stat.table(sex, mean(bweight), data=births)
```
## Measures of disease occurrence

### Prevenlence

```{r}
# prevalence = The prevalence of a disease in a population is the fraction of the population that has the disease at a given date

(16281/5534738) * 100 #empirical prevalence

# theoretical prevalence
#theoretical prevalence is the probability that a randomly chosen person from the
#population has colorectal cancer
library( Epi )
library(magrittr)
N <- 5534738
X <- 16281
mp <- glm( cbind( X, N-X ) ~ 1, family=binomial )
round( ci.pred( mp ) * 100, 4 )

```
### Mortality rate

```{r}
#Mortality is typically reported as a number of people that have died in a population #of a certain size

##Empirical mortality rate
(2648 / 150000)*1000
#This is a mortality of 17.6 per 1,000 without time correction
(2648 / (150000*2))*1000 # Mortality rate adjusted by two years

## Theoretical mortality rate
# It is the probability of dying in a small interval, relative to the length of the interval

library( Epi )
D <- 2648
Y <- 300000 #The double because 2 years
mm <- glm( D ~ 1, offset=log(Y), family=poisson )
round( ci.pred( mm, newdata=data.frame(Y=1000) ), 3 )

```

## Probabilidad

```{r}
library(Epi)
data(pr)
subset( pr, sex=="M" & A==60 )
```

## Prevalen by age



```{r}
prt <- stat.table( index = list(A, sex), 
                   contents = ratio(X, N, 100),
                   data = pr )[1,,]
#prevalencia de una enfermedead por sexo
matplot( 0:99+0.5, prt, type="l", lwd=2, col=c(4,2), lty=1 ) %>% abline( v=c(76,81)+0.5)


# Modelso pra predecir la prevalencia de una efermedad
pr$A <- pr$A+0.5
ma <- glm( cbind(X,N-X) ~ Ns( A, knots=c(10,30,50,60,70,80,90) ),
           family = binomial,
           data = subset(pr, sex=="M"))
fa <- glm( cbind(X,N-X) ~ Ns( A, knots=c(10,30,50,60,70,80,90) ),
           family = binomial,
           data = subset(pr, sex=="F"))
fa <- update( ma, data = subset(pr, sex=="F") )

## prediciones de los modelos

matplot( 0:99, prt, yaxs="i", ylim=c(0,20),
xlab="Age", ylab="Prevalence of diabetes 2010 (%)",
type="s", lwd=1, col=c("blue","red"), lty=1 )
nd <- data.frame( A=seq(0,100,0.2) )
pr.m <- ci.pred( ma, nd ) * 100
pr.f <- ci.pred( fa, nd ) * 100
matshade( nd$A, cbind(pr.m,pr.f), col=c("blue","red"), lwd=1, alpha=0.2 )
```

```{r}
#comparar modelos 

m1 <- glm( cbind(X,N-X) ~ Ns( A, knots=c(10, 50, 70, 90) ),
family = binomial, data = subset(pr,sex=="M") )
m2 <- glm( cbind(X,N-X) ~ Ns( A, knots=c(10,30,50,60, 70, 80,90) ),
family = binomial, data = subset(pr,sex=="M") )
m3 <- glm( cbind(X,N-X) ~ Ns( A, knots=c(10,30,50,60,65,70,75,80,90) ),
family = binomial, data = subset(pr,sex=="M") )
anova( m1, m2, m3, test="Chisq" )
```



